import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * CryptoQuant Terminal - Bootstrap Seed
 *
 * This seed creates MINIMAL bootstrap data so the app can start.
 * The REAL data comes from the RealDataLoader (triggered via /api/data-loader).
 *
 * What this creates:
 *   - 20 TradingSystem templates
 *   - 10 PatternRule templates
 *   - 8 TraderBehaviorModel entries (archetype × phase matrix)
 *   - 1 CapitalState (starting capital)
 *   - Core system configuration
 *
 * What this does NOT create (loaded by RealDataLoader):
 *   - Tokens (fetched from CoinGecko - 10,000+)
 *   - PriceCandles (fetched from CoinGecko OHLCV)
 *   - Traders (discovered from DexScreener/DexPaprika)
 *   - Signals (generated by brain pipeline)
 *   - TokenDNA (computed from market data)
 */

async function seed() {
  console.log('🚀 CryptoQuant Terminal — Bootstrap Seed starting...');
  const startTime = Date.now();

  // ============================================================
  // 1. CREATE TRADING SYSTEM TEMPLATES
  // ============================================================
  console.log('🎯 Creating Trading System templates...');

  const systemTemplates = [
    { name: 'Alpha Hunter', category: 'ALPHA_HUNTER', icon: '🎯', description: 'Early detection of emerging tokens with high growth potential' },
    { name: 'Smart Money Tracker', category: 'SMART_MONEY', icon: '🧠', description: 'Follow wallets with proven track records and high win rates' },
    { name: 'Technical Analyst', category: 'TECHNICAL', icon: '📊', description: 'Chart patterns, indicators, and multi-timeframe analysis' },
    { name: 'Defensive Shield', category: 'DEFENSIVE', icon: '🛡️', description: 'Capital preservation with strict risk management' },
    { name: 'Bot Aware', category: 'BOT_AWARE', icon: '🤖', description: 'Detect and avoid bot-manipulated tokens and wash trading' },
    { name: 'Deep Analyzer', category: 'DEEP_ANALYSIS', icon: '🔬', description: 'LLM-powered deep analysis with comprehensive evidence' },
    { name: 'Micro Structure', category: 'MICRO_STRUCTURE', icon: '⚡', description: 'Order book and micro-price action analysis' },
    { name: 'Adaptive Learner', category: 'ADAPTIVE', icon: '🔄', description: 'Self-improving system that learns from outcomes' },
    { name: 'Sniper Hunter', category: 'ALPHA_HUNTER', icon: '🔫', description: 'Detect tokens being targeted by sniper bots early' },
    { name: 'Whale Watcher', category: 'SMART_MONEY', icon: '🐋', description: 'Track large wallet movements and accumulation patterns' },
    { name: 'Momentum Rider', category: 'TECHNICAL', icon: '🏄', description: 'Ride strong momentum moves with trailing stops' },
    { name: 'Safe Harbor', category: 'DEFENSIVE', icon: '⚓', description: 'Ultra-conservative approach for bear markets' },
    { name: 'Anti-Wash Trade', category: 'BOT_AWARE', icon: '🚫', description: 'Filter out wash-traded volume and fake liquidity' },
    { name: 'Cross-Chain Scout', category: 'ALPHA_HUNTER', icon: '🔗', description: 'Find opportunities across multiple chains simultaneously' },
    { name: 'Liquidity Miner', category: 'SMART_MONEY', icon: '💧', description: 'Identify tokens with growing liquidity pools' },
    { name: 'Mean Reversion', category: 'TECHNICAL', icon: '↩️', description: 'Trade oversold/overbought conditions with statistical edges' },
    { name: 'Capital Guardian', category: 'DEFENSIVE', icon: '🏦', description: 'Maximum drawdown protection with dynamic position sizing' },
    { name: 'MEV Shield', category: 'BOT_AWARE', icon: '⚡', description: 'Protect against MEV extraction and sandwich attacks' },
    { name: 'Narrative Trader', category: 'DEEP_ANALYSIS', icon: '📰', description: 'AI-powered narrative and sentiment analysis' },
    { name: 'Regime Adapter', category: 'ADAPTIVE', icon: '🌍', description: 'Automatically adjust strategy based on market regime' },
  ];

  for (const tpl of systemTemplates) {
    await prisma.tradingSystem.upsert({
      where: { id: `template_${tpl.category}_${tpl.name.replace(/\s/g, '_')}` },
      update: {},
      create: {
        id: `template_${tpl.category}_${tpl.name.replace(/\s/g, '_')}`,
        name: tpl.name,
        description: tpl.description,
        category: tpl.category,
        icon: tpl.icon,
        assetFilter: JSON.stringify({ minVolume24h: 10000, minLiquidity: 5000 }),
        phaseConfig: JSON.stringify({ GENESIS: true, INCIPIENT: true, GROWTH: true, FOMO: false, DECLINE: false, LEGACY: false }),
        entrySignal: JSON.stringify({ type: 'composite', minConfidence: 0.6 }),
        executionConfig: JSON.stringify({ type: 'market', slippageToleranceBps: 100 }),
        exitSignal: JSON.stringify({ stopLossPct: 15, takeProfitPct: 40, trailingStopPct: 10 }),
        bigDataContext: JSON.stringify({ regime: ['BULL', 'SIDEWAYS'], volatility: ['NORMAL', 'LOW'] }),
        isActive: false,
        isPaperTrading: false,
      },
    });
  }
  console.log(`✅ Created ${systemTemplates.length} trading system templates`);

  // ============================================================
  // 2. CREATE PATTERN RULES
  // ============================================================
  console.log('📐 Creating Pattern Rules...');

  const patterns = [
    { name: 'Sudden Volume Spike', category: 'VOLUME', conditions: { volumeMultiplier: 5, minVolume24h: 100000, timeframe: '1h' } },
    { name: 'Price Dump with Recovery', category: 'PRICE', conditions: { dropThreshold: -15, recoveryPct: 5, timeframe: '4h' } },
    { name: 'Smart Money Accumulation', category: 'SMART_MONEY', conditions: { smartMoneyPct: 15, volume24h: 100000, priceChange24h: -5 } },
    { name: 'Liquidity Drain', category: 'LIQUIDITY', conditions: { liquidityDropPct: 30, volume24h: 50000 } },
    { name: 'Bot Activity Spike', category: 'BOT', conditions: { botActivityPct: 40, volume24h: 100000 } },
    { name: 'Rug Pull Pattern', category: 'RISK', conditions: { priceDrop24h: -50, liquidityBelow: 10000, holderCountBelow: 100 } },
    { name: 'Breakout Above Resistance', category: 'TECHNICAL', conditions: { priceChange1h: 5, volumeMultiplier: 3 } },
    { name: 'Dead Cat Bounce', category: 'RISK', conditions: { priceChange24h: -30, priceChange1h: 10, volumeDeclining: true } },
    { name: 'Whale Entry Signal', category: 'WHALE', conditions: { largeTxCount: 3, avgTxSize: 50000, timeframe: '6h' } },
    { name: 'Wash Trade Detection', category: 'BOT', conditions: { washTradeScore: 0.5, volumeToLiquidityRatio: 10 } },
  ];

  for (const p of patterns) {
    await prisma.patternRule.create({
      data: {
        name: p.name,
        category: p.category,
        conditions: JSON.stringify(p.conditions),
        isActive: true,
        winRate: 0.4 + Math.random() * 0.3,
        occurrences: Math.floor(Math.random() * 500),
      },
    });
  }
  console.log(`✅ Created ${patterns.length} pattern rules`);

  // ============================================================
  // 3. CREATE BEHAVIOR MODEL MATRIX (8 archetypes × 6 phases)
  // ============================================================
  console.log('🧬 Creating Behavior Model matrix...');

  const archetypes = ['SMART_MONEY', 'WHALE', 'SNIPER', 'RETAIL_FOMO', 'RETAIL_HOLDER', 'SCALPER', 'DEGEN', 'CONTRARIAN'];
  const phases = ['GENESIS', 'INCIPIENT', 'GROWTH', 'FOMO', 'DECLINE', 'LEGACY'];

  let modelCount = 0;
  for (const archetype of archetypes) {
    for (const phase of phases) {
      // Primary action depends on archetype + phase
      let action = 'HOLD';
      let probability = 0.3;
      let intensity = 0.1;
      let duration = 24;

      if (archetype === 'SMART_MONEY') {
        if (phase === 'GENESIS') { action = 'BUY'; probability = 0.6; intensity = 0.3; duration = 168; }
        else if (phase === 'GROWTH') { action = 'ACCUMULATE'; probability = 0.5; intensity = 0.2; duration = 72; }
        else if (phase === 'FOMO') { action = 'DISTRIBUTE'; probability = 0.7; intensity = 0.4; duration = 12; }
        else if (phase === 'DECLINE') { action = 'SELL'; probability = 0.5; intensity = 0.3; duration = 6; }
        else { action = 'WATCH'; probability = 0.4; intensity = 0.05; duration = 48; }
      } else if (archetype === 'WHALE') {
        if (phase === 'GENESIS' || phase === 'INCIPIENT') { action = 'ACCUMULATE'; probability = 0.4; intensity = 0.5; duration = 336; }
        else if (phase === 'FOMO') { action = 'DISTRIBUTE'; probability = 0.6; intensity = 0.6; duration = 24; }
        else { action = 'HOLD'; probability = 0.5; intensity = 0.1; duration = 720; }
      } else if (archetype === 'SNIPER') {
        if (phase === 'GENESIS') { action = 'BUY'; probability = 0.8; intensity = 0.8; duration = 0.5; }
        else if (phase === 'INCIPIENT') { action = 'SELL'; probability = 0.6; intensity = 0.7; duration = 1; }
        else { action = 'WATCH'; probability = 0.2; intensity = 0.05; duration = 0.5; }
      } else if (archetype === 'RETAIL_FOMO') {
        if (phase === 'FOMO') { action = 'BUY'; probability = 0.8; intensity = 0.6; duration = 24; }
        else if (phase === 'DECLINE') { action = 'SELL'; probability = 0.7; intensity = 0.5; duration = 6; }
        else { action = 'WATCH'; probability = 0.3; intensity = 0.1; duration = 48; }
      } else if (archetype === 'SCALPER') {
        action = 'BUY'; probability = 0.5; intensity = 0.4; duration = 0.5;
      } else if (archetype === 'DEGEN') {
        if (phase === 'GENESIS' || phase === 'INCIPIENT') { action = 'BUY'; probability = 0.7; intensity = 0.8; duration = 2; }
        else if (phase === 'DECLINE') { action = 'SELL'; probability = 0.6; intensity = 0.7; duration = 0.5; }
        else { action = 'HOLD'; probability = 0.3; intensity = 0.3; duration = 12; }
      } else if (archetype === 'CONTRARIAN') {
        if (phase === 'DECLINE') { action = 'BUY'; probability = 0.5; intensity = 0.3; duration = 168; }
        else if (phase === 'FOMO') { action = 'SELL'; probability = 0.5; intensity = 0.2; duration = 24; }
        else { action = 'WATCH'; probability = 0.4; intensity = 0.1; duration = 48; }
      } else {
        if (phase === 'GROWTH') { action = 'HOLD'; probability = 0.4; intensity = 0.15; duration = 336; }
        else { action = 'WATCH'; probability = 0.3; intensity = 0.05; duration = 48; }
      }

      await prisma.traderBehaviorModel.create({
        data: { archetype, tokenPhase: phase, action, probability, intensity, duration, observations: 0, confidence: 0 },
      });
      modelCount++;
    }
  }
  console.log(`✅ Created ${modelCount} behavior model entries`);

  // ============================================================
  // 4. CREATE INITIAL CAPITAL STATE
  // ============================================================
  console.log('💰 Creating initial capital state...');
  await prisma.capitalState.create({
    data: {
      totalCapitalUsd: 10,
      allocatedUsd: 0,
      availableUsd: 10,
      cycleCount: 0,
    },
  });

  // ============================================================
  // 5. CREATE DATA RETENTION POLICIES
  // ============================================================
  console.log('🗄️ Creating data retention policies...');
  const policies = [
    { dataType: 'SIGNALS', tableName: 'Signal', retentionDays: 30, hotDays: 7, warmDays: 14 },
    { dataType: 'CANDLES', tableName: 'PriceCandle', retentionDays: 90, hotDays: 7, warmDays: 30 },
    { dataType: 'TRANSACTIONS', tableName: 'TraderTransaction', retentionDays: 180, hotDays: 7, warmDays: 30 },
    { dataType: 'OPERABILITY', tableName: 'OperabilityScore', retentionDays: 30, hotDays: 3, warmDays: 7 },
    { dataType: 'PREDICTIVE_SIGNALS', tableName: 'PredictiveSignal', retentionDays: 90, hotDays: 7, warmDays: 30 },
    { dataType: 'DECISION_LOGS', tableName: 'DecisionLog', retentionDays: 365, hotDays: 7, warmDays: 30 },
  ];

  for (const policy of policies) {
    await prisma.dataRetentionPolicy.create({ data: policy });
  }
  console.log(`✅ Created ${policies.length} retention policies`);

  // ============================================================
  // DONE
  // ============================================================
  const elapsed = Date.now() - startTime;
  console.log(`🚀 Bootstrap seed COMPLETE in ${elapsed}ms`);
  console.log(`📊 Templates: ${systemTemplates.length} systems, ${patterns.length} patterns, ${modelCount} behavior models`);
  console.log(`💡 Next step: Call /api/data-loader with action='quick' or action='full' to load real token data`);
}

seed()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('❌ Seed failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
